Repository cm-rnd/item-module, pull requests merged in 2023-08, with the labels that each got.

#1 Kafka 설정 및 예시 작성
  build.gradle
  src/main/java/com/tmax/commerce/itemmodule/config/kafka/KafkaConsumerConfig.java
  src/main/java/com/tmax/commerce/itemmodule/config/kafka/KafkaProducerConfig.java
  src/main/java/com/tmax/commerce/itemmodule/config/kafka/KafkaProperty.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore

#2 옵션그룹, 옵션, 상품-옵션 릴레이션 엔티티 작성
  src/main/java/com/tmax/commerce/itemmodule/config/JpaAuditingConfig.java
  src/main/java/com/tmax/commerce/itemmodule/entity/BaseEntity.java
  src/main/java/com/tmax/commerce/itemmodule/entity/ItemOptionGroupRelation.java
  src/main/java/com/tmax/commerce/itemmodule/entity/Option.java
  src/main/java/com/tmax/commerce/itemmodule/entity/OptionGroup.java
  src/main/resources/application.yml
Labels: feature

#7 class import 오류 해결
  src/main/java/com/tmax/commerce/itemmodule/entity/base/BaseEntity.java
  src/main/java/com/tmax/commerce/itemmodule/entity/item/ItemOptionGroupRelation.java
  src/main/java/com/tmax/commerce/itemmodule/entity/option/Option.java
  src/main/java/com/tmax/commerce/itemmodule/entity/option/OptionGroup.java
Labels: fix

#11 [feat] 상품 등록 기능 구현
  src/main/java/com/tmax/commerce/itemmodule/common/UuidGenerator.java
  src/main/java/com/tmax/commerce/itemmodule/entity/category/Category.java
  src/main/java/com/tmax/commerce/itemmodule/entity/item/Item.java
  src/main/java/com/tmax/commerce/itemmodule/entity/item/ItemGroup.java
  src/main/java/com/tmax/commerce/itemmodule/entity/item/OrderType.java
  src/main/java/com/tmax/commerce/itemmodule/entity/item/subtyped/OnsiteItem.java
  src/main/java/com/tmax/commerce/itemmodule/entity/item/subtyped/PickupItem.java
  src/main/java/com/tmax/commerce/itemmodule/entity/option/ItemOptionGroupRelation.java
  src/main/java/com/tmax/commerce/itemmodule/repository/CategoryRepository.java
  src/main/java/com/tmax/commerce/itemmodule/repository/option/OptionGroupRepository.java
  src/main/java/com/tmax/commerce/itemmodule/service/command/ItemCommandService.java
  src/main/java/com/tmax/commerce/itemmodule/service/command/shop/owner/ItemCommand.java
Labels: feature

#12 [feat] 고객용 옵션 그룹 조회 기능 구현
  build.gradle
  src/main/java/com/tmax/commerce/itemmodule/controller/shop/customer/CustomerOptionGroupQueryController.java
  src/main/java/com/tmax/commerce/itemmodule/repository/option/ItemOptionGroupRelationRepository.java
  src/main/java/com/tmax/commerce/itemmodule/service/query/shop/customer/CustomerOptionGroupInfoMapper.java
  src/main/java/com/tmax/commerce/itemmodule/service/query/shop/customer/CustomerOptionGroupQuery.java
  src/main/java/com/tmax/commerce/itemmodule/service/query/shop/customer/CustomerOptionGroupQueryService.java
  src/main/java/com/tmax/commerce/itemmodule/service/query/shop/customer/info/CustomerOptionGroupInfo.java
Labels: feature
